/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreOutwardNewRouteImport } from './routes/store_.outward.new'
import { Route as StoreOutwardIdRouteImport } from './routes/store_.outward.$id'
import { Route as StoreInwardNewRouteImport } from './routes/store_.inward.new'
import { Route as StoreInwardIdRouteImport } from './routes/store_.inward.$id'
import { Route as StoreInstallerAddRouteImport } from './routes/store_.installer.add'
import { Route as StoreInstallerIdRouteImport } from './routes/store_.installer.$id'
import { Route as StoreB2bAddRouteImport } from './routes/store_.b2b.add'
import { Route as StoreB2bIdRouteImport } from './routes/store_.b2b.$id'
import { Route as InventoryProductNewRouteImport } from './routes/inventory_.product.new'
import { Route as InventoryOutwardNewRouteImport } from './routes/inventory_.outward.new'
import { Route as InventoryOutwardIdRouteImport } from './routes/inventory_.outward.$id'
import { Route as InventoryInwardNewRouteImport } from './routes/inventory_.inward.new'
import { Route as InventoryInwardIdRouteImport } from './routes/inventory_.inward.$id'
import { Route as InventoryInstallerAddRouteImport } from './routes/inventory_.installer.add'
import { Route as InventoryInstallerIdRouteImport } from './routes/inventory_.installer.$id'
import { Route as InventoryB2bAddRouteImport } from './routes/inventory_.b2b.add'
import { Route as InventoryB2bIdRouteImport } from './routes/inventory_.b2b.$id'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreOutwardNewRoute = StoreOutwardNewRouteImport.update({
  id: '/store_/outward/new',
  path: '/store/outward/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreOutwardIdRoute = StoreOutwardIdRouteImport.update({
  id: '/store_/outward/$id',
  path: '/store/outward/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreInwardNewRoute = StoreInwardNewRouteImport.update({
  id: '/store_/inward/new',
  path: '/store/inward/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreInwardIdRoute = StoreInwardIdRouteImport.update({
  id: '/store_/inward/$id',
  path: '/store/inward/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreInstallerAddRoute = StoreInstallerAddRouteImport.update({
  id: '/store_/installer/add',
  path: '/store/installer/add',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreInstallerIdRoute = StoreInstallerIdRouteImport.update({
  id: '/store_/installer/$id',
  path: '/store/installer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreB2bAddRoute = StoreB2bAddRouteImport.update({
  id: '/store_/b2b/add',
  path: '/store/b2b/add',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreB2bIdRoute = StoreB2bIdRouteImport.update({
  id: '/store_/b2b/$id',
  path: '/store/b2b/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryProductNewRoute = InventoryProductNewRouteImport.update({
  id: '/inventory_/product/new',
  path: '/inventory/product/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryOutwardNewRoute = InventoryOutwardNewRouteImport.update({
  id: '/inventory_/outward/new',
  path: '/inventory/outward/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryOutwardIdRoute = InventoryOutwardIdRouteImport.update({
  id: '/inventory_/outward/$id',
  path: '/inventory/outward/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryInwardNewRoute = InventoryInwardNewRouteImport.update({
  id: '/inventory_/inward/new',
  path: '/inventory/inward/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryInwardIdRoute = InventoryInwardIdRouteImport.update({
  id: '/inventory_/inward/$id',
  path: '/inventory/inward/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryInstallerAddRoute = InventoryInstallerAddRouteImport.update({
  id: '/inventory_/installer/add',
  path: '/inventory/installer/add',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryInstallerIdRoute = InventoryInstallerIdRouteImport.update({
  id: '/inventory_/installer/$id',
  path: '/inventory/installer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryB2bAddRoute = InventoryB2bAddRouteImport.update({
  id: '/inventory_/b2b/add',
  path: '/inventory/b2b/add',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryB2bIdRoute = InventoryB2bIdRouteImport.update({
  id: '/inventory_/b2b/$id',
  path: '/inventory/b2b/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRoute
  '/store': typeof StoreRoute
  '/inventory/b2b/$id': typeof InventoryB2bIdRoute
  '/inventory/b2b/add': typeof InventoryB2bAddRoute
  '/inventory/installer/$id': typeof InventoryInstallerIdRoute
  '/inventory/installer/add': typeof InventoryInstallerAddRoute
  '/inventory/inward/$id': typeof InventoryInwardIdRoute
  '/inventory/inward/new': typeof InventoryInwardNewRoute
  '/inventory/outward/$id': typeof InventoryOutwardIdRoute
  '/inventory/outward/new': typeof InventoryOutwardNewRoute
  '/inventory/product/new': typeof InventoryProductNewRoute
  '/store/b2b/$id': typeof StoreB2bIdRoute
  '/store/b2b/add': typeof StoreB2bAddRoute
  '/store/installer/$id': typeof StoreInstallerIdRoute
  '/store/installer/add': typeof StoreInstallerAddRoute
  '/store/inward/$id': typeof StoreInwardIdRoute
  '/store/inward/new': typeof StoreInwardNewRoute
  '/store/outward/$id': typeof StoreOutwardIdRoute
  '/store/outward/new': typeof StoreOutwardNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRoute
  '/store': typeof StoreRoute
  '/inventory/b2b/$id': typeof InventoryB2bIdRoute
  '/inventory/b2b/add': typeof InventoryB2bAddRoute
  '/inventory/installer/$id': typeof InventoryInstallerIdRoute
  '/inventory/installer/add': typeof InventoryInstallerAddRoute
  '/inventory/inward/$id': typeof InventoryInwardIdRoute
  '/inventory/inward/new': typeof InventoryInwardNewRoute
  '/inventory/outward/$id': typeof InventoryOutwardIdRoute
  '/inventory/outward/new': typeof InventoryOutwardNewRoute
  '/inventory/product/new': typeof InventoryProductNewRoute
  '/store/b2b/$id': typeof StoreB2bIdRoute
  '/store/b2b/add': typeof StoreB2bAddRoute
  '/store/installer/$id': typeof StoreInstallerIdRoute
  '/store/installer/add': typeof StoreInstallerAddRoute
  '/store/inward/$id': typeof StoreInwardIdRoute
  '/store/inward/new': typeof StoreInwardNewRoute
  '/store/outward/$id': typeof StoreOutwardIdRoute
  '/store/outward/new': typeof StoreOutwardNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRoute
  '/store': typeof StoreRoute
  '/inventory_/b2b/$id': typeof InventoryB2bIdRoute
  '/inventory_/b2b/add': typeof InventoryB2bAddRoute
  '/inventory_/installer/$id': typeof InventoryInstallerIdRoute
  '/inventory_/installer/add': typeof InventoryInstallerAddRoute
  '/inventory_/inward/$id': typeof InventoryInwardIdRoute
  '/inventory_/inward/new': typeof InventoryInwardNewRoute
  '/inventory_/outward/$id': typeof InventoryOutwardIdRoute
  '/inventory_/outward/new': typeof InventoryOutwardNewRoute
  '/inventory_/product/new': typeof InventoryProductNewRoute
  '/store_/b2b/$id': typeof StoreB2bIdRoute
  '/store_/b2b/add': typeof StoreB2bAddRoute
  '/store_/installer/$id': typeof StoreInstallerIdRoute
  '/store_/installer/add': typeof StoreInstallerAddRoute
  '/store_/inward/$id': typeof StoreInwardIdRoute
  '/store_/inward/new': typeof StoreInwardNewRoute
  '/store_/outward/$id': typeof StoreOutwardIdRoute
  '/store_/outward/new': typeof StoreOutwardNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inventory'
    | '/store'
    | '/inventory/b2b/$id'
    | '/inventory/b2b/add'
    | '/inventory/installer/$id'
    | '/inventory/installer/add'
    | '/inventory/inward/$id'
    | '/inventory/inward/new'
    | '/inventory/outward/$id'
    | '/inventory/outward/new'
    | '/inventory/product/new'
    | '/store/b2b/$id'
    | '/store/b2b/add'
    | '/store/installer/$id'
    | '/store/installer/add'
    | '/store/inward/$id'
    | '/store/inward/new'
    | '/store/outward/$id'
    | '/store/outward/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inventory'
    | '/store'
    | '/inventory/b2b/$id'
    | '/inventory/b2b/add'
    | '/inventory/installer/$id'
    | '/inventory/installer/add'
    | '/inventory/inward/$id'
    | '/inventory/inward/new'
    | '/inventory/outward/$id'
    | '/inventory/outward/new'
    | '/inventory/product/new'
    | '/store/b2b/$id'
    | '/store/b2b/add'
    | '/store/installer/$id'
    | '/store/installer/add'
    | '/store/inward/$id'
    | '/store/inward/new'
    | '/store/outward/$id'
    | '/store/outward/new'
  id:
    | '__root__'
    | '/'
    | '/inventory'
    | '/store'
    | '/inventory_/b2b/$id'
    | '/inventory_/b2b/add'
    | '/inventory_/installer/$id'
    | '/inventory_/installer/add'
    | '/inventory_/inward/$id'
    | '/inventory_/inward/new'
    | '/inventory_/outward/$id'
    | '/inventory_/outward/new'
    | '/inventory_/product/new'
    | '/store_/b2b/$id'
    | '/store_/b2b/add'
    | '/store_/installer/$id'
    | '/store_/installer/add'
    | '/store_/inward/$id'
    | '/store_/inward/new'
    | '/store_/outward/$id'
    | '/store_/outward/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InventoryRoute: typeof InventoryRoute
  StoreRoute: typeof StoreRoute
  InventoryB2bIdRoute: typeof InventoryB2bIdRoute
  InventoryB2bAddRoute: typeof InventoryB2bAddRoute
  InventoryInstallerIdRoute: typeof InventoryInstallerIdRoute
  InventoryInstallerAddRoute: typeof InventoryInstallerAddRoute
  InventoryInwardIdRoute: typeof InventoryInwardIdRoute
  InventoryInwardNewRoute: typeof InventoryInwardNewRoute
  InventoryOutwardIdRoute: typeof InventoryOutwardIdRoute
  InventoryOutwardNewRoute: typeof InventoryOutwardNewRoute
  InventoryProductNewRoute: typeof InventoryProductNewRoute
  StoreB2bIdRoute: typeof StoreB2bIdRoute
  StoreB2bAddRoute: typeof StoreB2bAddRoute
  StoreInstallerIdRoute: typeof StoreInstallerIdRoute
  StoreInstallerAddRoute: typeof StoreInstallerAddRoute
  StoreInwardIdRoute: typeof StoreInwardIdRoute
  StoreInwardNewRoute: typeof StoreInwardNewRoute
  StoreOutwardIdRoute: typeof StoreOutwardIdRoute
  StoreOutwardNewRoute: typeof StoreOutwardNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store_/outward/new': {
      id: '/store_/outward/new'
      path: '/store/outward/new'
      fullPath: '/store/outward/new'
      preLoaderRoute: typeof StoreOutwardNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store_/outward/$id': {
      id: '/store_/outward/$id'
      path: '/store/outward/$id'
      fullPath: '/store/outward/$id'
      preLoaderRoute: typeof StoreOutwardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store_/inward/new': {
      id: '/store_/inward/new'
      path: '/store/inward/new'
      fullPath: '/store/inward/new'
      preLoaderRoute: typeof StoreInwardNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store_/inward/$id': {
      id: '/store_/inward/$id'
      path: '/store/inward/$id'
      fullPath: '/store/inward/$id'
      preLoaderRoute: typeof StoreInwardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store_/installer/add': {
      id: '/store_/installer/add'
      path: '/store/installer/add'
      fullPath: '/store/installer/add'
      preLoaderRoute: typeof StoreInstallerAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store_/installer/$id': {
      id: '/store_/installer/$id'
      path: '/store/installer/$id'
      fullPath: '/store/installer/$id'
      preLoaderRoute: typeof StoreInstallerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store_/b2b/add': {
      id: '/store_/b2b/add'
      path: '/store/b2b/add'
      fullPath: '/store/b2b/add'
      preLoaderRoute: typeof StoreB2bAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store_/b2b/$id': {
      id: '/store_/b2b/$id'
      path: '/store/b2b/$id'
      fullPath: '/store/b2b/$id'
      preLoaderRoute: typeof StoreB2bIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory_/product/new': {
      id: '/inventory_/product/new'
      path: '/inventory/product/new'
      fullPath: '/inventory/product/new'
      preLoaderRoute: typeof InventoryProductNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory_/outward/new': {
      id: '/inventory_/outward/new'
      path: '/inventory/outward/new'
      fullPath: '/inventory/outward/new'
      preLoaderRoute: typeof InventoryOutwardNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory_/outward/$id': {
      id: '/inventory_/outward/$id'
      path: '/inventory/outward/$id'
      fullPath: '/inventory/outward/$id'
      preLoaderRoute: typeof InventoryOutwardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory_/inward/new': {
      id: '/inventory_/inward/new'
      path: '/inventory/inward/new'
      fullPath: '/inventory/inward/new'
      preLoaderRoute: typeof InventoryInwardNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory_/inward/$id': {
      id: '/inventory_/inward/$id'
      path: '/inventory/inward/$id'
      fullPath: '/inventory/inward/$id'
      preLoaderRoute: typeof InventoryInwardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory_/installer/add': {
      id: '/inventory_/installer/add'
      path: '/inventory/installer/add'
      fullPath: '/inventory/installer/add'
      preLoaderRoute: typeof InventoryInstallerAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory_/installer/$id': {
      id: '/inventory_/installer/$id'
      path: '/inventory/installer/$id'
      fullPath: '/inventory/installer/$id'
      preLoaderRoute: typeof InventoryInstallerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory_/b2b/add': {
      id: '/inventory_/b2b/add'
      path: '/inventory/b2b/add'
      fullPath: '/inventory/b2b/add'
      preLoaderRoute: typeof InventoryB2bAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory_/b2b/$id': {
      id: '/inventory_/b2b/$id'
      path: '/inventory/b2b/$id'
      fullPath: '/inventory/b2b/$id'
      preLoaderRoute: typeof InventoryB2bIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InventoryRoute: InventoryRoute,
  StoreRoute: StoreRoute,
  InventoryB2bIdRoute: InventoryB2bIdRoute,
  InventoryB2bAddRoute: InventoryB2bAddRoute,
  InventoryInstallerIdRoute: InventoryInstallerIdRoute,
  InventoryInstallerAddRoute: InventoryInstallerAddRoute,
  InventoryInwardIdRoute: InventoryInwardIdRoute,
  InventoryInwardNewRoute: InventoryInwardNewRoute,
  InventoryOutwardIdRoute: InventoryOutwardIdRoute,
  InventoryOutwardNewRoute: InventoryOutwardNewRoute,
  InventoryProductNewRoute: InventoryProductNewRoute,
  StoreB2bIdRoute: StoreB2bIdRoute,
  StoreB2bAddRoute: StoreB2bAddRoute,
  StoreInstallerIdRoute: StoreInstallerIdRoute,
  StoreInstallerAddRoute: StoreInstallerAddRoute,
  StoreInwardIdRoute: StoreInwardIdRoute,
  StoreInwardNewRoute: StoreInwardNewRoute,
  StoreOutwardIdRoute: StoreOutwardIdRoute,
  StoreOutwardNewRoute: StoreOutwardNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
